server:
    port: 8080
    context-path: /
    session:
        timeout: 3600
debug: false

mail:
  port: 25

spring:
    application:
       name: destiny
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://123.206.20.45:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
       username: root
       password: acedata1706
    http:
       encoding:
         charset: utf-8
         force: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      mode: HTML5

mybatis:
  type-aliases-package: com.acedata.boots.domain.ext
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true